### ISSUE TITLE
build error: AssertionError: Failed to run llvm optimizations

### ISSUE THREAD

**Issue by ddnionio** [tomasreimers/tensorflow-emscripten#1]
Hi
I am very interested in your project, but I met some problems while building it.

OS: Ubuntu 14.04
tensorflow-emscripten version : 18a6b98d77488086f24f6830f5b2db8667acc011 (the latest)

protoc version: 3.1.0
bazel version: 0.4.3
emscripten version: 1.36.5

 I tried to run the following 5 steps:
```
$ emconfigure ./configure
$ ./tensorflow/contrib/makefile_js/download_dependencies.sh
$ bazel build tensorflow/examples/label_image/...
$ ./tensorflow/contrib/makefile_js/gen_file_lists.sh
$ emmake make -f ./tensorflow/contrib/makefile_js/Makefile
```
it report error in the last command `$ emmake make -f ./tensorflow/contrib/makefile_js/Makefile`
```
Referencing global in another module!
i32* @_ZN6google8protobuf8internal14WireFormatLite23kMessageSetItemStartTagE
; ModuleID = '/tmp/tmpRxxgib/descriptor_dc5e3680.o'
i32* @_ZN6google8protobuf8internal14WireFormatLite23kMessageSetItemStartTagE
; ModuleID = '/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/gen/obj/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/programs/graph_runner/main.o'
Referencing global in another module!
i32* @_ZN6google8protobuf8internal14WireFormatLite21kMessageSetItemEndTagE
; ModuleID = '/tmp/tmpRxxgib/descriptor_dc5e3680.o'
i32* @_ZN6google8protobuf8internal14WireFormatLite21kMessageSetItemEndTagE
; ModuleID = '/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/gen/obj/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/programs/graph_runner/main.o'
Referencing global in another module!
i32* @_ZN6google8protobuf8internal14WireFormatLite20kMessageSetTypeIdTagE
; ModuleID = '/tmp/tmpRxxgib/descriptor_dc5e3680.o'
i32* @_ZN6google8protobuf8internal14WireFormatLite20kMessageSetTypeIdTagE
; ModuleID = '/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/gen/obj/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/programs/graph_runner/main.o'
Referencing global in another module!
i32* @_ZN6google8protobuf8internal14WireFormatLite21kMessageSetMessageTagE
; ModuleID = '/tmp/tmpRxxgib/descriptor_dc5e3680.o'
i32* @_ZN6google8protobuf8internal14WireFormatLite21kMessageSetMessageTagE
; ModuleID = '/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/gen/obj/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/programs/graph_runner/main.o'
Referencing global in another module!
i32* @_ZN6google8protobuf8internal14WireFormatLite23kMessageSetItemTagsSizeE
; ModuleID = '/tmp/tmpRxxgib/descriptor_dc5e3680.o'
i32* @_ZN6google8protobuf8internal14WireFormatLite23kMessageSetItemTagsSizeE
; ModuleID = '/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/gen/obj/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/programs/graph_runner/main.o'
Referencing global in another module!
[19 x i32]* @_ZN6google8protobuf8internal14WireFormatLite22kFieldTypeToCppTypeMapE
; ModuleID = '/tmp/tmpRxxgib/descriptor_dc5e3680.o'
[19 x i32]* @_ZN6google8protobuf8internal14WireFormatLite22kFieldTypeToCppTypeMapE
; ModuleID = '/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/gen/obj/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/programs/graph_runner/main.o'
Referencing global in another module!
[19 x i32]* @_ZN6google8protobuf8internal14WireFormatLite21kWireTypeForFieldTypeE
; ModuleID = '/tmp/tmpRxxgib/descriptor_dc5e3680.o'
[19 x i32]* @_ZN6google8protobuf8internal14WireFormatLite21kWireTypeForFieldTypeE
; ModuleID = '/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/gen/obj/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/programs/graph_runner/main.o'
All DICompileUnits must be listed in llvm.dbg.cu
/home/dd/emsdk/emsdk_portable/clang/fastcomp/build_master_64/bin/opt: /tmp/tmpRxxgib/descriptor_dc5e3680.o: error: input module is broken!
Traceback (most recent call last):
  File "/home/dd/emsdk/emscripten-1.36.5/emcc", line 13, in <module>
    emcc.run()
  File "/home/dd/emsdk/emscripten-1.36.5/emcc.py", line 1447, in run
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "/home/dd/emsdk/emscripten-1.36.5/tools/shared.py", line 1584, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations:
make: *** [/home/dd/ml/tf-em/tensorflow/contrib/makefile_js/gen/bin/graph_runner.js] Error 1
```

I see you mentions the similar problems in the `Known Issues`. Have you solved it yet? How can I build it in the ubuntu, or I have to build on Mac?

Thanks

**Comment by tomasreimers** [comment]
Hey ddnionio, 

Yeah, that's the same issue I was encountering on Ubuntu. It doesn't look like any of the other issues I've encountered doing this project.

I suspect it has to do with the linker flags on Ubuntu, check out https://github.com/tomasreimers/tensorflow-emscripten/blob/master/tensorflow/contrib/makefile_js/Makefile#L184, although I'm not sure and haven't had time to debug properly (aiming to release the proper pre-built JavaScript libraries in a week or so, so that people don't have to build it themselves). If you do want to build it yourself, I would really appreciate someone with a deep knowledge of emscripten or the linker to hop in here.  

Happy to talk about this issue more over email if you want! Just message me!

Best,
Tomas

**Comment by ddnionio** [comment]
I tried adding flag `-Wl,--whole-archive` for linux targert, which should be the replacement for `-all_load` in darwin. But it still report the same error.

**Comment by ddnionio** [comment]
Hi @tomasreimers  I maybe fix the issue by changing the `libprotobuf.a` to `libprotobuf.so` (which actually is bitcode)
`PROTOBUF_LIB := $(MAKEFILE_DIR)/downloads/protobuf-emscripten/src/.libs/libprotobuf.so`

But I am not sure whether it is really correct, because it still report some warning after linking.
```
warning: emitted code will contain very large numbers of local variables, which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')
warning: unresolved symbol: _ZN6google8protobuf53protobuf_InitDefaults_google_2fprotobuf_2fany_2eprotoEv
warning: unresolved symbol: _ZNK6google8protobuf3Any12ByteSizeLongEv
warning: unresolved symbol: _ZN6google8protobuf8internal26GeneratedMessageReflectionC1EPKNS0_10DescriptorEPKNS0_7MessageEPKiiiiPKNS0_14DescriptorPoolEPNS0_14MessageFactoryEii
warning: unresolved symbol: _ZNK6google8protobuf7Message12ByteSizeLongEv
warning: unresolved symbol: _ZN6google8protobuf21Any_default_instance_E
warning: unresolved symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE
```

Now, i have the `graph_runner.js` in `gen/bin`, but there is no `./run_scripts/run_labeler_c.sh`, it seems some contents in README is out-of-date.
Could you give me a simple case and example? so that I can check whether the transition is correct.
Thanks

**Comment by tomasreimers** [comment]
Generally those symbols mean that the program will throw a runtime error b/c there is an undefined function. One way to test this is to cd into graph_run_lib and do `node examples/example_with_lib.js`. The readme is out of date. Like I said in #2 , I have one major push coming soon (probably next week) which will include documentation and then I will turn my attention to Ubuntu.

**Comment by jiangzidong** [comment]
But there is no add_graph.pb in js_working_directory. I will try to create one simple pb and have a test. Looking forward to your update

**Comment by tomasreimers** [comment]
Attached! 

Yeah, excited that there's so much interest in this library, but it's not really ready for other people to start building on it just yet... The documentation is sparse and was intended more as notes for myself. The push will update all that though!

[add_graph.pb.zip](https://github.com/tomasreimers/tensorflow-emscripten/files/809391/add_graph.pb.zip)
